#include "credits.h"
#include <SDL2/SDL_blendmode.h> // Para SDL_BLENDMODE_BLEND
#include <SDL2/SDL_error.h>		// Para SDL_GetError
#include <SDL2/SDL_pixels.h>	// Para SDL_PIXELFORMAT_RGBA8888
#include <SDL2/SDL_rect.h>		// Para SDL_Rect
#include <SDL2/SDL_timer.h>		// Para SDL_GetTicks
#include <algorithm>			// Para min
#include <iostream>				// Para char_traits, basic_ostream, operator<<
#include "animatedsprite.h"		// Para AnimatedSprite
#include "const.h"				// Para GAMECANVAS_HEIGHT, GAMECANVAS_WIDTH
#include "input.h"				// Para Input, REPEAT_FALSE, inputs_e
#include "resource.h"			// Para Resource
#include "screen.h"				// Para Screen
#include "text.h"				// Para Text, TXT_CENTER, TXT_COLOR
#include "asset.h"
#include "options.h"
#include "global_inputs.h"
#include "global_events.h"
class Asset;

// Constructor
Credits::Credits()
	: screen_(Screen::get()),
	  renderer_(Screen::get()->getRenderer()),
	  resource_(Resource::get()),
	  asset_(Asset::get()),
	  input_(Input::get())
{
	// Reserva memoria para los punteros
	text_ = new Text(resource_->getOffset("smb2.txt"), resource_->getTexture("smb2.png"), renderer_);
	sprite_ = new AnimatedSprite(renderer_, resource_->getAnimation("shine.ani"));

	// Inicializa variables
	options.section.section = Section::CREDITS;
	options.section.subsection = Subsection::NONE;
	sprite_->setRect({194, 174, 8, 8});

	// Cambia el color del borde
	screen_->setBorderColor(stringToColor(options.video.palette, "black"));

	// Crea la textura para el texto que se escribe en pantalla
	text_texture_ = SDL_CreateTexture(renderer_, SDL_PIXELFORMAT_RGBA8888, SDL_TEXTUREACCESS_TARGET, GAMECANVAS_WIDTH, GAMECANVAS_HEIGHT);
	if (text_texture_ == nullptr)
	{
		if (options.console)
		{
			std::cout << "Error: textTexture could not be created!\nSDL Error: " << SDL_GetError() << std::endl;
		}
	}
	SDL_SetTextureBlendMode(text_texture_, SDL_BLENDMODE_BLEND);

	// Crea la textura para cubrir el rexto
	cover_texture_ = SDL_CreateTexture(renderer_, SDL_PIXELFORMAT_RGBA8888, SDL_TEXTUREACCESS_TARGET, GAMECANVAS_WIDTH, GAMECANVAS_HEIGHT);
	if (cover_texture_ == nullptr)
	{
		if (options.console)
		{
			std::cout << "Error: textTexture could not be created!\nSDL Error: " << SDL_GetError() << std::endl;
		}
	}
	SDL_SetTextureBlendMode(cover_texture_, SDL_BLENDMODE_BLEND);

	// Escribe el texto en la textura
	fillTexture();
}

// Destructor
Credits::~Credits()
{
	delete text_;
	delete sprite_;
	SDL_DestroyTexture(text_texture_);
	SDL_DestroyTexture(cover_texture_);
}

// Comprueba el manejador de eventos
void Credits::checkEvents()
{
	SDL_Event event;
	while (SDL_PollEvent(&event))
	{
		globalEvents::check(event);
	}
}

// Comprueba las entradas
void Credits::checkInput()
{
	globalInputs::check();
}

// Inicializa los textos
void Credits::iniTexts()
{
	std::string keys = "";
	if (options.keys == ControlScheme::CURSOR)
	{
		keys = "CURSORS";
	}
	else if (options.keys == ControlScheme::OPQA)
	{
		keys = "O,P AND Q";
	}
	else
	{
		keys = "A,D AND W";
	}

#ifndef GAME_CONSOLE
	texts_.clear();
	texts_.push_back({"", stringToColor(options.video.palette, "white")});
	texts_.push_back({"INSTRUCTIONS:", stringToColor(options.video.palette, "yellow")});
	texts_.push_back({"", stringToColor(options.video.palette, "white")});
	texts_.push_back({"HELP JAILDOC TO GET BACK ALL", stringToColor(options.video.palette, "white")});
	texts_.push_back({"HIS PROJECTS AND GO TO THE", stringToColor(options.video.palette, "white")});
	texts_.push_back({"JAIL TO FINISH THEM", stringToColor(options.video.palette, "white")});
	texts_.push_back({"", stringToColor(options.video.palette, "white")});
	texts_.push_back({"", stringToColor(options.video.palette, "white")});

	texts_.push_back({"KEYS:", stringToColor(options.video.palette, "yellow")});
	texts_.push_back({"", stringToColor(options.video.palette, "white")});
	texts_.push_back({keys + " TO MOVE AND JUMP", stringToColor(options.video.palette, "white")});
	texts_.push_back({"M TO SWITCH THE MUSIC", stringToColor(options.video.palette, "white")});
	texts_.push_back({"H TO PAUSE THE GAME", stringToColor(options.video.palette, "white")});
	texts_.push_back({"F1-F2 TO CHANGE WINDOWS SIZE", stringToColor(options.video.palette, "white")});
	texts_.push_back({"F3 TO SWITCH TO FULLSCREEN", stringToColor(options.video.palette, "white")});
	texts_.push_back({"B TO TOOGLE THE BORDER SCREEN", stringToColor(options.video.palette, "white")});
	texts_.push_back({"", stringToColor(options.video.palette, "white")});
	texts_.push_back({"", stringToColor(options.video.palette, "white")});

	texts_.push_back({"A GAME BY JAILDESIGNER", stringToColor(options.video.palette, "yellow")});
	texts_.push_back({"MADE ON SUMMER/FALL 2022", stringToColor(options.video.palette, "yellow")});
	texts_.push_back({"", stringToColor(options.video.palette, "white")});
	texts_.push_back({"", stringToColor(options.video.palette, "white")});

	texts_.push_back({"I LOVE JAILGAMES! ", stringToColor(options.video.palette, "white")});
	texts_.push_back({"", stringToColor(options.video.palette, "white")});
#else
	texts.clear();
	texts.push_back({"", stringToColor(options.video.palette, "white")});
	texts.push_back({"INSTRUCTIONS:", stringToColor(options.video.palette, "yellow")});
	texts.push_back({"", stringToColor(options.video.palette, "white")});
	texts.push_back({"HELP JAILDOC TO GET BACK ALL", stringToColor(options.video.palette, "white")});
	texts.push_back({"HIS PROJECTS AND GO TO THE", stringToColor(options.video.palette, "white")});
	texts.push_back({"JAIL TO FINISH THEM", stringToColor(options.video.palette, "white")});
	texts.push_back({"", stringToColor(options.video.palette, "white")});
	texts.push_back({"", stringToColor(options.video.palette, "white")});

	texts.push_back({"KEYS:", stringToColor(options.video.palette, "yellow")});
	texts.push_back({"", stringToColor(options.video.palette, "white")});
	texts.push_back({"B TO JUMP", stringToColor(options.video.palette, "white")});
	texts.push_back({"R TO SWITCH THE MUSIC", stringToColor(options.video.palette, "white")});
	texts.push_back({"L TO SWAP THE COLOR PALETTE", stringToColor(options.video.palette, "white")});
	texts.push_back({"START TO PAUSE", stringToColor(options.video.palette, "white")});
	texts.push_back({"SELECT TO EXIT", stringToColor(options.video.palette, "white")});
	texts.push_back({"", stringToColor(options.video.palette, "white")});
	texts.push_back({"", stringToColor(options.video.palette, "white")});
	texts.push_back({"", stringToColor(options.video.palette, "white")});

	texts.push_back({"A GAME BY JAILDESIGNER", stringToColor(options.video.palette, "yellow")});
	texts.push_back({"MADE ON SUMMER/FALL 2022", stringToColor(options.video.palette, "yellow")});
	texts.push_back({"", stringToColor(options.video.palette, "white")});
	texts.push_back({"", stringToColor(options.video.palette, "white")});

	texts.push_back({"I LOVE JAILGAMES! ", stringToColor(options.video.palette, "white")});
	texts.push_back({"", stringToColor(options.video.palette, "white")});
#endif
}

// Escribe el texto en la textura
void Credits::fillTexture()
{
	// Inicializa los textos
	iniTexts();

	// Rellena la textura de texto
	SDL_SetRenderTarget(renderer_, text_texture_);
	Color c = stringToColor(options.video.palette, "black");
	SDL_SetRenderDrawColor(renderer_, c.r, c.g, c.b, 0xFF);
	SDL_RenderClear(renderer_);

	// Escribe el texto en la textura
	const int size = text_->getCharacterSize();
	int i = 0;

	for (auto t : texts_)
	{
		text_->writeDX(TXT_CENTER | TXT_COLOR, PLAY_AREA_CENTER_X, i * size, t.label, 1, t.color);
		i++;
	}

	// Escribe el corazón
	const int textLenght = text_->lenght(texts_[22].label, 1) - text_->lenght(" ", 1); // Se resta el ultimo caracter que es un espacio
	const int posX = ((PLAY_AREA_WIDTH - textLenght) / 2) + textLenght;
	text_->writeColored(posX, 176, "}", stringToColor(options.video.palette, "bright_red"));

	// Recoloca el sprite del brillo
	sprite_->setPosX(posX + 2);

	SDL_SetRenderTarget(renderer_, nullptr);

	// Rellena la textura que cubre el texto con color transparente
	SDL_SetRenderTarget(renderer_, cover_texture_);
	SDL_SetRenderDrawColor(renderer_, c.r, c.g, c.b, 0x00);
	SDL_RenderClear(renderer_);

	// Los primeros 8 pixels crea una malla
	SDL_SetRenderDrawColor(renderer_, c.r, c.g, c.b, 0xFF);
	for (int i = 0; i < 256; i += 2)
	{
		SDL_RenderDrawPoint(renderer_, i, 0);
		SDL_RenderDrawPoint(renderer_, i, 2);
		SDL_RenderDrawPoint(renderer_, i, 4);
		SDL_RenderDrawPoint(renderer_, i, 6);

		SDL_RenderDrawPoint(renderer_, i + 1, 5);
		SDL_RenderDrawPoint(renderer_, i + 1, 7);
	}

	// El resto se rellena de color sólido
	SDL_Rect rect = {0, 8, 256, 192};
	SDL_RenderFillRect(renderer_, &rect);

	SDL_SetRenderTarget(renderer_, nullptr);
}

// Actualiza el contador
void Credits::updateCounter()
{
	// Incrementa el contador
	if (counter_enabled_)
	{
		counter_++;
		if (counter_ == 224 || counter_ == 544 || counter_ == 672)
		{
			counter_enabled_ = false;
		}
	}
	else
	{
		sub_counter_++;
		if (sub_counter_ == 100)
		{
			counter_enabled_ = true;
			sub_counter_ = 0;
		}
	}

	// Comprueba si ha terminado la sección
	if (counter_ > 1200)
	{
		options.section.section = Section::DEMO;
	}
}

// Actualiza las variables
void Credits::update()
{
	// Comprueba que la diferencia de ticks sea mayor a la velocidad del juego
	if (SDL_GetTicks() - ticks_ > ticks_speed_)
	{
		// Actualiza el contador de ticks
		ticks_ = SDL_GetTicks();

		// Comprueba las entradas
		checkInput();

		// Actualiza el contador
		updateCounter();

		screen_->update();

		// Actualiza el sprite con el brillo
		if (counter_ > 770)
		{
			sprite_->update();
		}
	}
}

// Dibuja en pantalla
void Credits::render()
{
	// Prepara para empezar a dibujar en la textura de juego
	screen_->start();

	// Limpia la pantalla
	screen_->clean();

	if (counter_ < 1150)
	{
		// Dibuja la textura con el texto en pantalla
		SDL_RenderCopy(renderer_, text_texture_, nullptr, nullptr);

		// Dibuja la textura que cubre el texto
		const int offset = std::min(counter_ / 8, 192 / 2);
		SDL_Rect srcRect = {0, 0, 256, 192 - (offset * 2)};
		SDL_Rect dstRect = {0, offset * 2, 256, 192 - (offset * 2)};
		SDL_RenderCopy(renderer_, cover_texture_, &srcRect, &dstRect);

		// Dibuja el sprite con el brillo
		sprite_->render();
	}

	// Vuelca el contenido del renderizador en pantalla
	screen_->render();
}

// Bucle para el logo del juego
void Credits::run()
{
	while (options.section.section == Section::CREDITS)
	{
		update();
		checkEvents();
		render();
	}
}

// Cambia la paleta
void Credits::switchPalette()
{
	options.video.palette = options.video.palette == Palette::ZXSPECTRUM ? Palette::ZXARNE : Palette::ZXSPECTRUM;
	fillTexture();
}